name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.242.131.247 << 'EOF'
            cd /var/www/react-app
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx
          EOF
